language: cpp

compiler:
  - clang
  - gcc

before_install:
 - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
 - sudo apt-get update -qq
 - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; fi
 - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
 - sudo apt-get install -qq cmake libboost-all-dev libfuse-dev libgtest-dev

before_script:
- mkdir build
- cd build

script:
- cmake .. && cmake --build .

after_script:
- ctest -V .
