language: cpp

compiler:
  - clang
  - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libboost-dev libgtest-dev

before_script:
- mkdir build
- cd build

script:
- cmake .. && cmake --build . --target install

after_script:
- ctest -V .
